AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        GIN_MODE: release

Resources:

  ExpensesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ExpensesApi
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: expenses_table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: expenseID
          AttributeType: S
      KeySchema:
        - AttributeName: expenseID
          KeyType: HASH

  ExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Events:
        GetExpenses:
          Type: Api
          Properties:
            Path: /expenses
            Method: GET
            RestApiId: !Ref ExpensesApi
        CreateExpense:
          Type: Api
          Properties:
            Path: /expenses
            Method: POST
            RestApiId: !Ref ExpensesApi
        OptionsExpenses:
          Type: Api
          Properties:
            Path: /expenses
            Method: OPTIONS
            RestApiId: !Ref ExpensesApi
        UpdateExpense:
          Type: Api
          Properties:
            Path: /expenses/{id}
            Method: PUT
            RestApiId: !Ref ExpensesApi
        DeleteExpense:
          Type: Api
          Properties:
            Path: /expenses/{id}
            Method: DELETE
            RestApiId: !Ref ExpensesApi
        OptionsExpenseById:
          Type: Api
          Properties:
            Path: /expenses/{id}
            Method: OPTIONS
            RestApiId: !Ref ExpensesApi
      Environment:
        Variables:
          EXPENSES_TABLE_NAME: !Ref ExpensesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
    Metadata:
      BuildMethod: makefile
